blank_issues_enabled: true
contact_links:
  - name: Discussion Forum
    url: https://visual-layer.readme.io/discuss
    about: Ask questions and discuss.
  - name: Discord Channel
    url: https://discord.gg/tkYHJCA7mb
    about: Chat with us.
  - name: Documentation Page
    url: https://visual-layer.readme.io/
    about: Read the docs.